---
title: "Homework 2"
author: "Eshaan Singh (es45858)"
date: "2025-01-28"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(ggplot2)
library(tidyverse)
```

## Part 1

```{r}
data <- read.csv('profs.csv')
ggplot(data) + geom_histogram(color ="black", aes(x = eval)) + labs(x = "Course evaluation scores", y = "How many students contributed", title = "Distribution of Course Evaluation Scores")
```
```{r}
ggplot(data) + geom_boxplot(aes(x = native, y = eval)) + labs(x = "If teacher is native in speaking English", y = "Course evaluation score", title = "Impact of Native English Speaking Teachers on Course Evaluation Scores")
```
```{r}
ggplot(data) + geom_histogram(color ="black",aes(y =eval)) + labs(x = "Number of Students who filled out the course evaluation", y = "Course Evaluation Score", title = "Impact of Course Evaluation Score based on Gender") + facet_wrap(~gender)
```
```{r}
ggplot(data) + geom_point(aes(x = beauty, y = eval)) + labs(x = "Subjective beauty rating", y= "Course evaluation score", title = "Impact of beauty on course evaluation score")
```


## Part 2


```{r}
bike <- read.csv("bikeshare.csv")
bike |> group_by(hr) |> summarise(avg_total = mean(total)) |> ggplot() + geom_line(aes(x = hr, y = avg_total)) + labs(title = "Average Hourly Bike Rentals", x = "Hour of the Day", y = "Average Bike Rentals")

```

```{r}
bike |> 
  group_by(hr, workingday) |> summarise(avg_total = mean(total)) |> ggplot() + geom_line(aes(x = hr, y = avg_total)) + 
  labs(title = "Average Hourly Bike Rentals", x = "Hour of the Day", y = "Average Bike Rentals") + facet_wrap(~workingday)
```


```{r}
bike |> filter(hr == 9) |> group_by(weathersit, workingday) |> ggplot() + geom_bar(aes(x = weathersit)) + facet_wrap(~workingday) + labs(x = "weather situation code", y = "Frequency of Bike-sharing rentals", title = "Frequency of Bike-sharing rentals based on weather situation code")
```

## Part 3
```{r}

# Recode the categorical variables in sensible, rather than alphabetical, order
capmetro_UT <- read.csv('capmetro_UT.csv')
capmetro_UT = mutate(capmetro_UT,
day_of_week = factor(day_of_week,
levels=c("Mon", "Tue", "Wed","Thu", "Fri", "Sat", "Sun")),
month = factor(month,
levels=c("Sep", "Oct","Nov")))
```

```{r}
capmetro_UT |> group_by(hour_of_day, month, day_of_week) |> summarise(avgBoard = mean(boarding)) |> ggplot() + geom_line(aes(x = hour_of_day, y = avgBoard, color = month)) + facet_wrap(~day_of_week) + labs(x = "Hour of the day", y = "Average boardings", title = "Average boardings based on the hour of day over different months")
```
```{r}
capmetro_UT |> ggplot() + geom_point(aes(x = boarding, y= temperature, color = weekend)) + facet_wrap(~hour_of_day)
```

## Part 4

```{r}
billboard <- read.csv('billboard.csv')
top_songs <- billboard |> group_by(performer, song) |> summarise(count = n(), .groups = "drop") |> arrange(desc(count)) |> 
slice_head(n = 10)
knitr::kable(top_songs)
```

```{r}
billboard |> filter(year!=1958, year!=2021) |> group_by(year) |> summarise(count = n_distinct(song), .groups = "drop") |> ggplot() + geom_line(aes(x = year, y = count)) + labs(x = "Year of song Release", y = "Number of Unique songs", title = "Number of unique songs over the years")
```

```{r}
billboard |> group_by(performer) |> filter(weeks_on_chart >= 10) |> summarise(counts = n_distinct(song), .groups = "drop") |> 
filter(counts >= 30) |> ggplot(aes(x = fct_reorder(performer, counts), y = counts)) + geom_bar(stat = "identity") + labs(x = "Artist", y = "Number of 10-week-hits produced", title = "Number of 10-week-hits artists top produced") + coord_flip() 
```
## NEED CAPTIONS FOR PLOTS GENERATED
- key takeaways and and features 
